import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
    return (
        <>
            <Head>
                <title>T.C. Cox Software Engineer</title>
                <meta name="A website to showcase the Front-End development skills of T.C." content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.center}>
                    <h1>Thomas &quot;T.C.&quot; Cox</h1>
                </div>
                <div className={styles.description}>
                    <div className={styles.cursor} /><h2>Meta&reg;-Certified Front-End Engineer</h2>
                </div>
                <div className={styles.grid}>
                    <Link href="about" className={styles.card}>
                        <h2>
                            About <span>-&gt;</span>
                        </h2>
                        <p>
                            Find in-depth information about Next.js features and&nbsp;API.
                        </p>
                    </Link>

                    <a
                        href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2>
                            My Work <span>-&gt;</span>
                        </h2>
                        <p>
                            Take a look at muy projects and some of what&nbsp;I can do!
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2>
                            Contact <span>-&gt;</span>
                        </h2>
                        <p>
                            Reach out and touch me...on social media.
                        </p>
                    </a>
                </div>
            </main>
        </>
    )
}
